stages:
  - setup
  - lint
  - test
  - deploy

variables:
  VENV: .venv
  FLASK_ENV: production

setup:
  stage: setup
  image: python:3.12
  script:
    - python -m venv $VENV
    - source $VENV/bin/activate
    - pip install --upgrade pip
    - pip install -r requirements.txt
  artifacts:
    paths:
      - $VENV

lint:
  stage: lint
  image: python:3.12
  script:
    - source $VENV/bin/activate
    - pip install flake8
    - flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics

test:
  stage: test
  image: python:3.12
  script:
    - source $VENV/bin/activate
    - pip install pytest
    - pytest tests/

deploy:
  stage: deploy
  image: python:3.12
  script:
    - source $VENV/bin/activate
    - gunicorn -w 2 -b 0.0.0.0:5000 app:app
  only:
    - main
